#pragma once
#define MCME_SUCCESS 0x00
#define MCME_FAILURE 0x01
#define MCME_FILE_NOT_FOUND 0x02
#define MCME_OUT_OF_MEMORY 0x03
#define MCME_INPUT_REQUIRED 0x04
#define MCME_ILLFORMED_NBT 0x10
#define MCME_FINISHED_NBT 0x11
#define MCME_OUT
#define MCME_OUT_OPT